export interface PropertyDetailType {
    id:string,
    featured: boolean,
    name: string,
    description: string,
    type: string,
    category: string,
    price: number,
    currency: string,
    location: string,
    size: number,
    constructed: number,
    bedrooms: number,
    bathrooms: number,
    kitchen: number,
    garage: number,
    others: Array<string>,
    services: Array<string>,
    amenities: Array<string>,
    images: Array<{id:string,url:string}>
}

export interface PropertyType {
    id:string,
    featured: boolean,
    name: string,
    description: string,
    type: string,
    category: string,
    price: number,
    currency: string,
    location: string,
    size: number,
    constructed: number,
    bedrooms: number,
    bathrooms: number,
    kitchen: number,
    garage: number,
    others: Array<string>,
    services: Array<string>,
    amenities: Array<string>,
}